import Head from "next/head";

export default function Blog(props) {

    function deletePost() {
      console.log("hello");
      const val = document.getElementById("blogID").value;
      console.log(val);
      try {
        fetch("http://localhost:3000/blog/delete/" + val, { method: "DELETE"});
      }catch (e) {
        console.error(e);
      }
    }
    function hello() {
      console.log("hello");
    }

    return (
      <section>
        <Head>
          <title>GoingVoip Blogs</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
  
        <main>
          <div>
            Blog section
          </div>
          <input type="number" name="blog_id" id="blogID"/>
          <button onClick={deletePost}>Delete</button>
        </main>
      </section>
    )
  }