import Head from 'next/head';

import ContactUsDisplay from "../components/ContactUs/ContactUsDisplay";

export default function contactUs() {
    return(
        <div>
            <Head>
                <title>Contact Us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <ContactUsDisplay />
            </main>
        </div>
    );
}