import Head from 'next/head';


import ContactUs from '../components/ContactUs/ContactUs';

export default function contactUs() {
    return(
        <div>
            <Head>
                <title>Contact Us</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <ContactUs />
            </main>
        </div>
    );
}