import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import { useState } from "react";

import Welcome from "../components/Welcome";
import CardSection from "../components/CardSection";

import styles from '../styles/Home.module.css'
import "bootstrap/dist/css/bootstrap.min.css";


export default function Home(props) {
  const [state, setState] = useState(0);

  function up() {
    setState(state + 1);
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Welcome count={state}/>
        <CardSection />
      </main>
    </div>
  )
}
